[package]
name = "ascii-in-the-park"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
crossterm = "0.28.1"
image = "0.24.6"
imageproc = { version = "0.23.0" }
ratatui = "0.28.1"
rusttype = "0.9.3"
